# Includes gcc, cmake
FROM mcr.microsoft.com/vscode/devcontainers/cpp:0-debian-11

ENTRYPOINT ["/bin/bash"]

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends libcurl4-nss-dev
